#!/usr/bin/env python3
import requests
import os
import sys

def get_current_day():
    day = sys.argv[1] if len(sys.argv) > 1 else None
    if day:
        return day
    cwd = os.getcwd().split('/')[-1]
    assert cwd.startswith("d")
    cwd = int(cwd[1:])
    assert 1 <= cwd <= 25
    return cwd

day = get_current_day()

cookies = {'session': os.environ['AOC_COOKIE']}


r = requests.get(f"https://adventofcode.com/2024/day/{day}/input", cookies=cookies);
input = r.text

assert not os.path.isfile("input.txt")

with open("input.txt", "w") as f:
    f.write(input)
