[package]
name = "d13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "5", features = ["fancy"] }
nom = "7"
nom-supreme = "0.8"
nom_locate = "4"
thiserror = "1.0.37"
